### ISSUE TITLE
Some 3-byte characters get an error when decoding.

### ISSUE THREAD

**Issue by goya813** [ixmilia/dxf-rs#13]
Hi I met build error on Mac OS.
The system requirements are as follows

macOS Catalina
cargo 1.46.0 (149022b1d 2020-07-17)
rustc 1.46.0 (04488afe3 2020-08-24)
dxf-rs 0.4.0

As an example, this happens when the following data is read as UTF-8.

````
0
SECTION
2
TABLES
0
TABLE
2
LAYER
100
AcDbSymbolTable
70
0
0
LAYER
2
ｱｲｿﾒ
0
ENDTAB
0
ENDSEC
0
EOF
````

"ｱｲｿﾒ" is a 3-byte character.
Perhaps the problem is that it is escaped as a UTF-8 BOM when the first character is "0xEF".
https://github.com/ixmilia/dxf-rs/blob/main/src/helper_functions.rs#L292-L295

In UTF-8, "ｱｲｿﾒ" seems to have been skipped by one byte because all "ｱｲｿﾒ" is prefixed with "0xEF" (https://www.utf8-chartable.de/unicode-utf8-table.pl?start=65280&utf8=dec).

Thank you for a great project!!

Translated with www.DeepL.com/Translator (free version)

**Comment by brettfo** [comment]
Thank you for the detailed issue.  I've fixed the bug in commit 9fbd4b7edd87a4b7df85b6044f9a90db4913c76c.
