### ISSUE TITLE
Fail parsing on empty $FINGERPRINTGUID and $VERSIONGUID

### ISSUE THREAD

**Issue by kurtlawrence** [ixmilia/dxf-rs#21]
Hi there,

I am receiving a parsing error for the attached DXF file. 
[out1.zip](https://github.com/ixmilia/dxf-rs/files/6794737/out1.zip)

If I remove the lines 950-957 it successfully parses. The contents of those lines is as follows:
```
$FINGERPRINTGUID
  2

  9
$VERSIONGUID
  2

  9
```

I am wondering if it is possible to have a loading mechanism that is tolerant of these empty entries?

**Comment by kurtlawrence** [comment]
Looks like it is related to: https://github.com/IxMilia/Dxf/issues/83

**Comment by brettfo** [comment]
Good call, and you're right, the fix was exactly the same as the C# version of this library.  I've pushed a commit that covers this case.
