### ISSUE TITLE
Encountering ParseError

### ISSUE THREAD

**Issue by kurtlawrence** [ixmilia/dxf-rs#22]
Hi there, I am encountering a parse error with the following files attached.
[parse-errors.zip](https://github.com/ixmilia/dxf-rs/files/7151787/parse-errors.zip)

It looks like it is on the `$HANDSEED` header.

**Comment by brettfo** [comment]
Thanks for filing the issue!  There is whitespace around the `$HANDSEED` value that I didn't properly account for.  I've fixed that in commit 00a62846e4d42f854e125964b807b3aaf81fec7e.

**Comment by kurtlawrence** [comment]
I appreciate the speedy response!
