### ISSUE TITLE
BufReader and BufWriter

### ISSUE THREAD

**Issue by rradev** [ixmilia/dxf-rs#33]
For large DXF files, for performance reasons, it make sense to have the possibility to set the buffer size.

[let mut buf_reader = BufReader::new(file);](https://github.com/ixmilia/dxf-rs/blob/43200fb358305647d4279902fd5818705cc34652/src/drawing.rs#L164)

[let mut writer = BufWriter::new(file);](https://github.com/ixmilia/dxf-rs/blob/43200fb358305647d4279902fd5818705cc34652/src/drawing.rs#L219)

for example:
`let mut buf_reader = BufReader::with_capacity(buff_size, file);`

The DEFAULT_BUF_SIZE is 8KB

**Comment by brettfo** [comment]
You can create your own `BufReader` with any size and directly call [`load_with_encoding(&mut my_reader, encoding_rs::WINDOWS_1252)`](https://github.com/ixmilia/dxf-rs/blob/8f44c7722a457d4c58a0e6b64cc71d8a3fdde228/src/drawing.rs#L114) to load from anything that implements `Read`.
