### ISSUE TITLE
Add LwPolyline elevation

### ISSUE THREAD

**Issue by Yairama** [ixmilia/dxf-rs#39]
Hello!

I've been trying to get the elevation of the LwPolyline but I can't find it anywhere.
![image](https://user-images.githubusercontent.com/45445692/233831834-f7cb0984-225c-48ef-a06e-df14d6d93d92.png)

I thought it was the bulge parameter but it is not, it always gives me zero.

Can you add it please?

**Comment by Yairama** [comment]
guess fixed at [#40](https://github.com/ixmilia/dxf-rs/pull/40)

**Comment by brettfo** [comment]
`elevation` is a field on the `common` entity properties.  I've pushed commit 041cdfc56ed9ba31359ae0441ae56caf16e31a5d to `main` that has tests that shows how to get and set this value.
