### ISSUE TITLE
Is a closed polyline missing nodes

### ISSUE THREAD

**Issue by c5cle** [ixmilia/dxf-rs#45]
This is a closed polyline rectangle, but there are only 4 nodes in the read data, missing the last closed node
![image](https://github.com/ixmilia/dxf-rs/assets/56671041/835b3f28-b26f-46c5-808c-9f174068735d)

**Comment by c5cle** [comment]
This uses files from dxf 2013
[test2013.zip](https://github.com/ixmilia/dxf-rs/files/11811728/test2013.zip)

**Comment by ykong1337** [comment]
> This is a closed polyline rectangle, but there are only 4 nodes in the read data, missing the last closed node ![image](https://user-images.githubusercontent.com/56671041/247380155-835b3f28-b26f-46c5-808c-9f174068735d.png)

Note members: ```flags```
When it is 1 it means closure, you need to draw closure yourself. ``` 1 -> 2 -> 3 -> 4 -> 1 ```
You can ignore it when it is 0. ``` 1 -> 2 -> 3 -> 4 ```

**Comment by c5cle** [comment]
> > This is a closed polyline rectangle, but there are only 4 nodes in the read data, missing the last closed node ![image](https://user-images.githubusercontent.com/56671041/247380155-835b3f28-b26f-46c5-808c-9f174068735d.png)
> 
> Note members: `flags` When it is 1 it means closure, you need to draw closure yourself. `1 -> 2 -> 3 -> 4 -> 1` You can ignore it when it is 0. `1 -> 2 -> 3 -> 4`

thanks.
