### ISSUE TITLE
The output dxf cannot be open in AutoCAD and Teighaviewer once AcadVersion is set

### ISSUE THREAD

**Issue by piaoger** [IxMilia/dxf-rs#6]
I found output dxf files cannot be open once I set AcadVersion. 
The attached "file-r12.dxf" and "file-r2004" are generated with below functions.
 
I also found below error in Teigha converter：
 ```
ODA Warning: Syntax error or premature end of file on line/offset 972.
OdError thrown during readFile of drawing "/Users/piaoger/Documents/DWG/i/file-r2004.dxf" :
  Null object Id: <object> (0)
```

- my code to generate dxf file:

```
fn test_dxf_default_r12(){
    let mut drawing = Drawing::default();
    drawing.entities.push(
        entities::Entity::new(
            entities::EntityType::Line(
                entities::Line::new(
                    dxf::Point::new (0.0, 0.0,0.0),
                    dxf::Point::new (5.0, 5.0,0.0),
                )
            )
        )
    );

    drawing.save_file("./file-r12.dxf").unwrap();
}

fn test_dxf_r2014(){
    let mut drawing = Drawing::default();
    drawing.header.version = AcadVersion::R2004;
    drawing.entities.push(
        entities::Entity::new(
            entities::EntityType::Line(
                entities::Line::new(
                    dxf::Point::new (0.0, 0.0,0.0),
                    dxf::Point::new (5.0, 5.0,0.0),
                )
            )
        )
    );
    drawing.save_file("./file-r2004.dxf").unwrap();
}

```

[dxffiles.zip](https://github.com/IxMilia/dxf-rs/files/2266006/dxffiles.zip)

**Comment by brettfo** [comment]
I only have the Teigha Viewer to test with, but I'm able to write an R2004 file by adding the following line:

``` diff
  let mut drawing = Drawing::default();
+ drawing.normalize();
  drawing.header.version = AcadVersion::R2004;
```

The issue is that AutoCAD (and apparently Teigha) are very particular about the layout of the file, specifically requiring certain objects to be present which the `normalize()` method adds as appropriate.

This does lead to a question of how this library should handle drawing creation.  Using `Drawing::default()` results in an empty struct and as a result a nearly empty file; would you find it beneficial to have a constructor that does the following?

``` rust
impl Drawing
{
    // ...
    pub fn new() -> Self { // I'm open to naming suggestions if `new` isn't descriptive enough
        let mut drawing = Drawing::default();
        drawing.normalize();
        drawing
    }
    // ...
}
```

There is certainly the issue of documentation; the sample only shows the `Drawing::default()` approach, I presume it would be good to show the usage of `normalize()`, too, or would the alternate constructor be sufficient?

**Comment by piaoger** [comment]
For viewing DXF, I also use [Autodesk Online Viewer](https://viewer.autodesk.com] which is baked by AutoCAD.

After calling normalize, The output DXF files can be opened  by Teigha viewer, but still failed in Inkscape and Autodesk viewer. To work with them, I have to "normalize" again the dxf files with Teigha Converter though file size is much larger:)

**Comment by piaoger** [comment]
It seems that this crate is still not very robust yet  and I have already resolved my issue :)

**Comment by brettfo** [comment]
> It seems that this crate is still not very robust

That's absolutely true, but I'd like to improve it where possible.

> I have already resolved my issue

Did you resolve it by normalizing again (presumably open and re-save) via the Teigha Converter, or something else.  If something else can you share what you used so I can try to replicate it?

**Comment by piaoger** [comment]
@brettfo 

You guys have already done great job 👍  

Yes. My re-normalized is just opening and saving  dxf via Teigha Converter. Without it, it cannot be opened in Autodesk products. 
-  I can try QCAD today and let you know the result.
-  I can also share you some almost empty dxf files, containing only one or line entity, generated from if you need.

**Comment by piaoger** [comment]
I tried QCAD just now, it works well. It seems that dxf load/save is built on Teigha :)
