### ISSUE TITLE
DWG support

### ISSUE THREAD

**Issue by happydpc** [ixmilia/dxf-rs#8]
There's a repo [libredwg  ](https://github.com/LibreDWG/libredwg) that seems very nice. Do you have an interest in implementing a DWG one.

**Comment by brettfo** [comment]
Unfortunately I don't have the time to dedicate to implementing a DWG reader/writer, however the Open Design Alliance has published a specification of the DWG file format that's available [here](https://www.opendesign.com/files/guestdownloads/OpenDesign_Specification_for_.dwg_files.pdf).
